### ISSUE TITLE
Will you be showing CI across platforms?

### ISSUE THREAD

**Issue by 456dev** [finneyj/SaadBall#7] opened 2024-02-27 17:19 UTC
I.E.
github actions here
gitlab workflows on https://scc-source.lancs.ac.uk

**Comment by aaronkellyuk** [comment] 2024-02-27 17:42
Duplicate of 6, but with less detail.

**Comment by ezzini** [comment] 2024-02-27 21:16
Not enough time today :(

**Closed as completed by ezzini** 2024-02-27 21:16 UTC
